### ISSUE TITLE
Feedback.

### ISSUE THREAD

**Issue by sajanssens** [robbd2020/labs#1]
https://github.com/robbd2020/labs/blob/a49d4abd9326d86827271fa30b1ea110a2010a0b/src/main/java/h7/PersonDiedException.java#L4

- Je kunt beter overerven van Exception of RTE. 
- Je kunt beter het veld message uit de super class hergebruiken. Dat houdt in een eigen ctor aanmaken: ...(String m){ super(m);}

**Comment by robbd2020** [comment]
- Erft nu van Exception

- Het message veld van de super class wordt nu gebruikt door de string in een aangemaakte constructor mee te geven
